### PR TITLE
Center logo in README.MD

### PR DESCRIPTION
**Pull request by CaenJones**

### CODE REVIEW

**Comment by quackduck** [comment]
You're cutting a lot of documentation from the page. Your PR says this is a reformat, but it actually edits a lot of the actual content. I like the idea of centering the logo.

**Comment by CaenJones** [comment]
True, but most of the documentation is just copied from the chats help menus or available on the admins or integration manuals. They do not need to be included on the README and add unnecessary clutter.

**Comment by CaenJones** [comment]
But I did bring back some things that might be useful

**Comment by quackduck** [comment]
I'm sorry, I don't really see this PR adding much in its current state.
image

**Pull request merged**
