### PR TITLE
Implement bans based on user id

### PR DESCRIPTION
**Pull request by TommyPujol06**
I still need to work out how to get the user IP so atm I'm banning based on the user id.

### CODE REVIEW

**Comment by quackduck** [comment]
I don't really see a need for this just yet, but you can go ahead and add it in:

You'll need to add a command in the repl() function. We'll also need persistence: see how I use gob to put the allUsers info into a file

**Comment by TommyPujol06** [comment]
Yes I just realized that lol, implementing it rn. I think it's useful to avoid the 100 ishan's situation.

**Comment by quackduck** [comment]
well i fixed the spoofing issue but yes the command might come in useful as devsat (devzat?) grows

**Comment by quackduck** [comment]
I merged it from the command line! Thanks for your help! Because of conflicts, it won't let me merge it right from here.

**Comment by quackduck** [comment]
@TommyPujol06 if you could just pull from main i can merge this thing (github won't let me merge it)

It is already merged into main, it's just that it doesn't show up as so.

**Comment by quackduck** [comment]
wth why won't github let me merge

**Comment by quackduck** [comment]
@TommyPujol06 reopen this

**Comment by quackduck** [comment]
Also, just add a random file so it lets me merge it

Then, I'll try to change the author of your commit to you

**Comment by TommyPujol06** [comment]
opened

**Pull request merged**
