### PR TITLE
Add Magic-8-Ball function

### PR DESCRIPTION
**Pull request by CaenJones**
It is fun!

### CODE REVIEW

**Comment by CaenJones** [comment]
Why it not working?!?!?!?!?!

**Comment by PPTide** [comment]
You are printing to the console not actually to devzat xD

**Comment by PPTide** [comment]
U can use `u.room.broadcast("8-ball", response)`

**Comment by quackduck** [comment]
This would make for an excellent plugin!

**Comment by CaenJones** [comment]
Thanks!

**Pull request closed without merging**
