### PR TITLE
Major refactor

### PR DESCRIPTION
**Pull request by gravestench**
building off of #108

it compiles now, everything is decoupled. Still doesn't boot all the way up, but I'm close. There's some logic i still need to change regarding default files either need to be created during init, or just loaded, but that shouldn't take too long. 

After I get it running again, I'll start absorbing all of the recent commits (~23 of them if i'm counting correctly).

### CODE REVIEW

**Comment by gravestench** [comment]
```bash
dk@pancake:~/src/devzat$ go run ./cmd/devzat-server/
```
```
2022/04/08 16:51:35 bans.go:71: open bans.json: no such file or directory
2022/04/08 16:51:35 server.go:73: Did not find twitter-creds.json. Enabling offline mode.
Starting chat server on port 22 and profiling on port 5555
```

**Comment by quackduck** [comment]
Epic, I'd love to try it out if you've got it hosted somewhere

**Comment by gravestench** [comment]
i may be done for the day, it'll probably be another hour or two of work to get it fully operational.

**Comment by gravestench** [comment]
got it working
image

**Comment by gravestench** [comment]
the server config struct writes itself as a `.env` now

here's what it currently looks like:
```shell
### [ Runtime ]
### settings for the devzat runtime
# DEVZAT_PORT=22
# DEVZAT_PROFILEPORT=5555
# DEVZAT_SCROLLBACKHISTORY=16
DEVZAT_CFGDIR=/home/dk/.config/devzat-server
DEVZAT_CFGFILENAME=config.env

### [ Anti-spam ]
### settings for controlling spam
# DEVZAT_SPAM_WINDOW=5s
# DEVZAT_SPAM_LIMITWARN=30
# DEVZAT_SPAM_LIMITBAN=50
# DEVZAT_SPAM_BANDURATION=5m0s

### [ Slack ]
### settings for slack integration
# DEVZAT_SLACK_OFFLINE=true

### [ Twitter ]
### settings for twitter integration
# DEVZAT_TWITTER_OFFLINE=true
```

**Pull request closed without merging**
