### PR TITLE
Add recommended specs to admins manual

### PR DESCRIPTION
**Pull request by CaenJones**
It is what it says

### CODE REVIEW

**Comment by quackduck** [comment]
How did you come up with these specs?

**Comment by CaenJones** [comment]
I ran devzat in a VM at home. This was the area where it preformed well with the least processing power

**Comment by quackduck** [comment]
I'm pretty sure the main Devzat instance has an internet speed available to it measured in kbps

**Comment by CaenJones** [comment]
what would you recommend it being then?

**Comment by quackduck** [comment]
Usually people only add in recommended specs when some sort of quite heavy application is being run. Devzat is text based (thus not needing much network bandwidth) and uses barely any memory or storage.

**Comment by CaenJones** [comment]
it would make it so they do not over-allocate resources for the hosting

**Comment by quackduck** [comment]
Yeah we could add in a lil note about how devzat is so lightweight you could even run it on a base level raspberry pico or something.

**Comment by CaenJones** [comment]
ok then, one sec...

**Comment by quackduck** [comment]
"20 GB Storage" makes it seem like Devzat itself will take up at least 20 gigs of storage

**Comment by CaenJones** [comment]
ok, I changed it

**Comment by quackduck** [comment]
Currently the data storage on the main server is 15 mb for the executable + 5 mb for user data

**Comment by quackduck** [comment]
Let me just confirm it will actually run on a pico. Asking around...

**Comment by CaenJones** [comment]
works with pi zero, will post extensive guide soon :P

**Comment by CaenJones** [comment]
wat

**Comment by quackduck** [comment]
this is my reaction too

**Pull request closed without merging**
