### PR TITLE
Add :wq as an alias of exit

### PR DESCRIPTION
**Pull request by PPTide**
Because my fingers are faster than my Brain :)

### CODE REVIEW

**Comment by quackduck** [comment]
Do we really need two vim exit aliases

**Comment by PPTide** [comment]
yes! yes we do... xD

**Comment by Arkaeriit** [comment]
> Do we really need two vim exit aliases

Yes

**Comment by PPTide** [comment]
Thanks for agreeing with me xD

Sent with Spark

**Pull request merged**
