### PR TITLE
added links of hack clubbers

### PR DESCRIPTION
**Pull request by tanishq-soni**

### CODE REVIEW

**Comment by quackduck** [comment]
Oh when you first proposed this I thought you meant github links but sure, this works too!

**Comment by quackduck** [comment]
Also, some people are left out from the conversion?

**Comment by tanishq-soni** [comment]
@quackduck done 👍🏻

**Comment by quackduck** [comment]
Perfect! Thanks for your contribution to Devzat!

**Comment by tanishq-soni** [comment]
Yay! Devzat to the moon 🚀 🌔

**Pull request merged**
