### PR TITLE
Changing nickname keep the user's color.

### PR DESCRIPTION
**Pull request by Arkaeriit**

### CODE REVIEW

**Comment by quackduck** [comment]
This should be handled inside `pickUsername` which is the reason the colors change.

**Comment by Arkaeriit** [comment]
You are right. Maybe pickUsername shouldn't change the color in the first place?

**Comment by quackduck** [comment]
Yes, that's what I've been working on coincidentally.

**Comment by quackduck** [comment]
was fixed in https://github.com/quackduck/devzat/commit/0e0ef1a5c79983ed3ef3dc545f4dac31b79a9098

**Pull request closed without merging**
