### PR TITLE
Commands v2

### PR DESCRIPTION
**Pull request by TAG-Epic**
This is a continuation of #34

### CODE REVIEW

**Comment by quackduck** [comment]
Thanks for re-opening

**Comment by quackduck** [comment]
@TAG-Epic could you change the base branch to `v2`

**Comment by TAG-Epic** [comment]
> @TAG-Epic could you change the base branch to `v2`

Any reason for this?

**Comment by quackduck** [comment]
Makes it easier for me to make changes :)

**Comment by quackduck** [comment]
https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request

**Comment by TAG-Epic** [comment]
I've given you permission to edit my branch.

**Pull request closed without merging**
