### PR TITLE
Clarify the nickname documentation

### PR DESCRIPTION
**Pull request by Arkaeriit**
The info is not really clear as showed by multiple new users being called 'nickname' each time Devzat is advertised in a new place.

### CODE REVIEW

**Comment by quackduck** [comment]
approve!!

**Comment by quackduck** [comment]
hey @Arkaeriit you should do the merge

**Comment by Arkaeriit** [comment]
What does "wenjie" mean?

**Comment by Arkaeriit** [comment]
Ho, right, it's the first important character in the Three Body Problem.

**Comment by quackduck** [comment]
yup :)

**Pull request merged**
