### PR TITLE
Make tic-tac-toe interface cleaner

### PR DESCRIPTION
**Pull request by TommyPujol06**
Automate the printing of the board and add numbers to the cell number, so it's easier for the user.

Image of new board: https://i.ibb.co/xGF5pnS/pic-selected-210519-2033-34.png

I also added this message, so the user knows what to do.
> devbot: To make your move type /tic <move>

### CODE REVIEW

**Comment by quackduck** [comment]
I've tried the numbers thing, see the comments above your changes to the tttPrint func. They look good at the start of the game but then when people start playing, the "O" and "X" don't look so nice. So I even tried to use unicode subscript numbers, but that didn't look great either.

I like the changed message, but the user still doesn't know what a "<move>" actually is, so could you make the message "Play using /tic <cell num>", which is short and clear enough.

Thanks for your help with Devzat!

**Comment by TommyPujol06** [comment]
Ok, I'll try to fix that today.

**Comment by quackduck** [comment]
Dunno if it rendered correctly in the mail but I meant the improved message to have `<cell num`. (md interpreted it as html angle brackets)

**Comment by quackduck** [comment]
Could you instead check if the game is new by checking if the array of cells is made of empty cells? Also, let the code to actually do the printing remain:
```go
	var buf bytes.Buffer
	fmt.Fprintf(&buf, " %v │ %v │ %v \n", strcells[0], strcells[1], strcells[2])
	fmt.Fprintln(&buf, "───┼───┼───")
	fmt.Fprintf(&buf, " %v │ %v │ %v \n", strcells[3], strcells[4], strcells[5])
	fmt.Fprintln(&buf, "───┼───┼───")
	fmt.Fprintf(&buf, " %v │ %v │ %v ", strcells[6], strcells[7], strcells[8])
```

**Comment by TommyPujol06** [comment]
I messed up something with git and now there are many commits in here. I'm currently trying to fix it.

**Comment by TommyPujol06** [comment]
OK, the issue has been fixed.

**Comment by quackduck** [comment]
No problem

**Comment by quackduck** [comment]
Love it! Thanks for helping Devzat!

**Pull request merged**
