### PR TITLE
Mention WolfRam Alpha in README + Admin's Manual

### PR DESCRIPTION
**Pull request by CaenJones**

### CODE REVIEW

**Comment by Arkaeriit** [comment]
As the wolf commands comes from a plugin, it doesn't feel wise to mention it here. If someone wants to self-host Devzat, they won't have that command available and they might be confused.

If we want to acknowledge the plugins, we might have a list of all known plugins somewhere, but I don't think we should do more.

**Comment by CaenJones** [comment]
I see

**Comment by quackduck** [comment]
We should definitely have a list of plugins maybe near the bottom of the readme. thoughts, @Arkaeriit?

**Comment by Arkaeriit** [comment]
> We should definitely have a list of plugins maybe near the bottom of the readme. thoughts, @Arkaeriit?

I think you're right. I will open an issue so that we can start to curate a list.

**Pull request closed without merging**
