### PR TITLE
New admin ids

### PR DESCRIPTION
**Pull request by TAG-Epic**

### CODE REVIEW

**Comment by quackduck** [comment]
ummm do you really need _that_ many

**Comment by TAG-Epic** [comment]
No but it was funny

**Comment by quackduck** [comment]
7 is too much

**Comment by TAG-Epic** [comment]
> 7 is too much
> 

All of them are in use

**Review by CaenJones — APPROVED** [review]

**Comment by quackduck** [comment]
Pick the 3 most important ones. Also you know you can use the same keys for different machines right

**Comment by TAG-Epic** [comment]
> Pick the 3 most important ones. Also you know you can use the same keys when connecting to Devzat for different machines right

Yes, but I want to keep them seperated.

**Comment by TAG-Epic** [comment]
Right so 3 included.

**Comment by quackduck** [comment]
Alright. I don’t see why you don’t reserve one key for use with Devzat and use that on each machine. I’m curious how you’ll use these ids.

**Pull request merged**
